apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cws
    component: scheduler
    tier: control-plane
  name: workflow-scheduler
  namespace: example
spec:
  hostname: workflow-scheduler
  containers:
  - env:
    - name: SCHEDULER_NAME
      value: workflow-scheduler
    - name: AUTOCLOSE
      value: "false"
    image: commonworkflowscheduler/kubernetesscheduler:latest
    imagePullPolicy: Always
    name: workflow-scheduler
    resources:
      limits:
        cpu: "2"
        memory: 1400Mi
      requests:
        cpu: "2"
        memory: 1400Mi
    volumeMounts:
    - mountPath: /nfs/input
      name: vol-1
#  nodeSelector:
#    cwsscheduler: 'true'
  securityContext:
    runAsUser: 0
  serviceAccount: sauser
  volumes:
  - name: vol-1
    persistentVolumeClaim:
      claimName: workspace-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cws-service
  namespace: example
spec:
  selector:
    app: cws
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

