apiVersion: v1
kind: Namespace
metadata:
  name: example

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: example
  name: sauser

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: example
  name: example-role
rules:
  - apiGroups: [""]
    resources: ["pods","pods/status","pods/log","pods/exec","nodes","bindings","configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: example
  name: example-rolebind
roleRef:
  kind: ClusterRole
  name: example-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: sauser
    namespace: example

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: example
  name: workspace-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G

